version: "3"

services:
  postgres:
    image: postgres
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports: 
      - "5432:5432"
    volumes:
      - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
  
  server:
    build:
      context: ../server
    ports:
      - "5000:5000"
    volumes:
      - "../server:/app"
    depends_on:
      - postgres
