version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    networks:
      - app_network

  server:
    build:
      context: ../server # Adjusted path to point to the 'server' folder outside 'docker'
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ../server:/app # Adjusted volume mount to use the correct server path
    environment:
      - DATABASE_URL=postgres://postgres:docker@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
